name: Build ICS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    paths:
      - "transform.py"
      - "requirements.txt"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Generate transformed ICS
        run: python transform.py

      - name: Commit feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/feed.ics
          git commit -m "Update feed" || echo "No changes"
          git push || true
