name: Build ICS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # 6 óránként
  push:
    paths:
      - "transform.py"
      - "requirements.txt"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate transformed ICS
        run: python transform.py

      - name: Commit feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/feed.ics
          git commit -m "Update feed" || echo "No changes"
          git push || true

      - name: Upload artifact (Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
